version: "3"

services:
  react:
    build: .
    image: acgomes68/alpine-node:latest
    restart: always
    container_name: react-${APP_NAME}
    command: npm start
    ports:
    - ${REACT_APP_PORT}:3000
    volumes:
    - .:/usr/app
