version: "3"

services:
  node:
    build: .
    depends_on:
      - postgres
    image: acgomes68/alpine-node:latest
    restart: always
    container_name: node-${API_NAME}
    command: npm start
    ports:
    - ${API_PORT}:3000
    volumes:
    - ./backend:/usr/app

  react:
    build: .
    depends_on:
      - node
    image: acgomes68/alpine-node:latest
    restart: always
    container_name: react-${APP_NAME}
    command: npm start
    ports:
    - ${APP_PORT}:3000
    volumes:
    - ./frontend:/usr/app

  postgres:
    image: postgres:11-alpine
    restart: always
    container_name: postgres-${POSTGRES_DATABASE}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
    - ./backend/data/postgres:/var/lib/postgresql/data
